---
- name:   Switch Audio Output to USB
  become: True
  replace:
    path:    /usr/share/alsa/alsa.conf
    regexp:  '(?<=defaults\..{3}\.card\s)(0)'
    replace: '1'
    backup:  Yes

- name:   Update streaming bitrate
  become: True
  replace:
    path:    /etc/default/raspotify
    regexp:  '.?BITRATE=.*'
    replace: "BITRATE=\"{{ spotify_client.bitrate }}\""

- name:   Change Client name
  become: True
  replace:
    path:    /etc/default/raspotify
    regexp:  '.?DEVICE_NAME=.*'
    replace: "DEVICE_NAME=\"{{ spotify_client.name }}\""

- name:   Change Spotify Credentials
  become: True
  replace:
    path:    /etc/default/raspotify
    regexp:  '.?OPTIONS=.*'
    replace: "OPTIONS=\"--username {{ spotify_client.username }} --password {{ spotify_client.password }}\""

- name:   Restart Raspotify
  become: True
  systemd:
    name:          raspotify
    daemon_reload: yes
    state:         restarted