---
- name:   Switch Audio Output to USB
  become: True
  replace:
    path:    /usr/share/alsa/alsa.conf
    regexp:  '(?<=defaults\..{3}\.card\s)(0)'
    replace: '1'
    backup:  Yes

- name:   Update streaming bitrate
  become: True
  replace:
    path:    /etc/raspotify/conf
    regexp:  '.?LIBRESPOT_BITRATE=.*'
    replace: "LIBRESPOT_BITRATE=\"{{ spotify_client.bitrate }}\""

- name:   Change Client name
  become: True
  replace:
    path:    /etc/raspotify/conf
    regexp:  '.?LIBRESPOT_NAME=.*'
    replace: "LIBRESPOT_NAME=\"{{ spotify_client.name }}\""

- name:   Change Username
  become: True
  replace:
    path:    /etc/raspotify/conf
    regexp:  '.?LIBRESPOT_USERNAME=.*'
    replace: "LIBRESPOT_USERNAME=\"{{ spotify_client.username }}\""

- name:   Change Password
  become: True
  replace:
    path:    /etc/raspotify/conf
    regexp:  '.?LIBRESPOT_PASSWORD=.*'
    replace: "LIBRESPOT_PASSWORD=\"{{ spotify_client.password }}\""

- name:   Restart Raspotify
  become: True
  systemd:
    name:          raspotify
    daemon_reload: yes
    state:         restarted